<?php

namespace Boleto\Repositories\Eloquent;

use Boleto\Models\Address;
use Boleto\Models\Person;
use Boleto\Repositories\EloquentRepository;
use Illuminate\Database\Eloquent\Model;

class PersonRepository extends EloquentRepository
{
    public function __construct()
    {
        parent::__construct(new Person());
    }

    public function get()
    {
        return parent::get(); // TODO: Change the autogenerated stub
    }

    public function create(array $data): Model
    {
        return parent::create($data);
    }

    public function find(int $id): Model
    {
        return parent::find($id); // TODO: Change the autogenerated stub
    }

    public function update(array $data, int $id): Model
    {
        return parent::update($data, $id); // TODO: Change the autogenerated stub
    }

    public function delete(int $id): Model
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function createOrUpdate(array $data): Model
    {
        $query = $this->get()->toQuery()->where('cpf_cnpj','=',$data['cpf_cnpj']);
        $person = $query->exists() ? $this->update($data, $query->get()->first()->id) : $this->create($data);
        array_key_exists('phone', $data) ? resolve(PhoneRepository::class)->createOrUpdate($data['phone'])
            : resolve(PhoneRepository::class)->create(['ddd' => 0, 'number' => 0, 'person_id' => $person->id]);
        array_key_exists('address', $data) ? resolve(AddressRepository::class)->createOrUpdate($data['address'])
            : null;
        array_key_exists('email', $data) ?
            resolve(EmailRepository::class)
                ->createOrUpdate(array_key_exists($data['email'],['person_id' => $person->id]))
            : null;
        return $person;
    }

}
