<?php

namespace Boleto\Providers;

use Boleto\Console\BoletoConsole;

class ServiceProvider extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {
        $this->publishes([
            __DIR__ . '/../../config/laravel-boleto.php' => config_path('boleto.php'),
        ]);
        $this->loadMigrationsFrom([
            __DIR__ . '/../../database/migrations'
        ]);
        if ($this->app->runningInConsole()) {
            $this->commands([
                BoletoConsole::class
            ]);
        }
        $this->mergeConfigFrom(
            __DIR__ . '/../../config/laravel-boleto.php', 'boleto'
        );
    }

}
